# version: "3.8"

services:
  mtc_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mtc_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - mtcnet

  mtc_nginx:
    image: nginx:alpine
    container_name: mtc_nginx
    restart: unless-stopped
    ports:
      - "8585:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mtc_app
    networks:
      - mtcnet

  # Optional: Redis for caching/sessions
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - mtcnet

networks:
  mtcnet:
    driver: bridge
